backend:
  name: git-gateway
  branch: master  # Change to "main" if your repo uses "main"

media_folder: "static/uploads" # Folder for uploaded media
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Published", name: "published", widget: "boolean" }