backend:
  name: auth0
  auth_endpoint: "https://dev-ggrjli7t.auth0.com"
  application_id: "ED3NMMgKYMVhcHVdK4s3zj570E9puao4"
  app_identifier: "faustinog.netlify.app"
  site_id: "02a5e5ec-cd6d-4507-aeb7-7acae6d98d6a"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Published"
        name: "published"
        widget: "boolean"